import * as SecureStore from 'expo-secure-store';
import { Platform } from 'react-native';

const BYOK_STORAGE_KEY = 'rootforge.gemma.api-key';
const GEMMA_MODEL = 'gemma-4-26b-a4b-it';

export type AgentPermission = 'read' | 'edit' | 'create' | 'delete' | 'terminal' | 'install' | 'internet' | 'commit';

export type AgentRequest = {
  prompt: string;
  projectName: string;
  projectPath: string;
  workspaceTree: string[];
  permissions: AgentPermission[];
};

export type AgentPlan = {
  summary: string;
  filesToCreate: string[];
  filesToModify: string[];
  filesToDelete: string[];
  commands: string[];
  rawResponse: string;
};

export type AgentExecutionOperation = {
  type: 'write_file' | 'delete_path';
  path: string;
  content?: string;
  rationale: string;
};

export type AgentExecutionRequest = AgentRequest & {
  approvedCreates: string[];
  approvedModifies: string[];
  approvedDeletes: string[];
  fileContext: Array<{
    path: string;
    content: string;
  }>;
};

export type AgentExecutionPlan = {
  summary: string;
  operations: AgentExecutionOperation[];
  rawResponse: string;
};

export async function saveBringYourOwnKey(apiKey: string) {
  if (Platform.OS === 'web') {
    localStorage.setItem(BYOK_STORAGE_KEY, apiKey.trim());
    return;
  }

  await SecureStore.setItemAsync(BYOK_STORAGE_KEY, apiKey.trim());
}

async function getBringYourOwnKey() {
  if (Platform.OS === 'web') {
    return localStorage.getItem(BYOK_STORAGE_KEY)?.trim() ?? '';
  }

  return (await SecureStore.getItemAsync(BYOK_STORAGE_KEY))?.trim() ?? '';
}

export async function hasBringYourOwnKey() {
  return Boolean(await getBringYourOwnKey());
}

function extractJsonBlock(text: string) {
  const fenced = text.match(/```(?:json)?\s*([\s\S]*?)```/i);
  if (fenced) {
    return fenced[1].trim();
  }

  const firstBrace = text.indexOf('{');
  const lastBrace = text.lastIndexOf('}');
  if (firstBrace === -1 || lastBrace === -1 || lastBrace <= firstBrace) {
    throw new Error('Gemma did not return a JSON plan.');
  }

  return text.slice(firstBrace, lastBrace + 1);
}

function toStringArray(value: unknown) {
  if (!Array.isArray(value)) {
    return [];
  }

  return value
    .map((item) => String(item).trim())
    .filter(Boolean);
}

function normalizeOperation(value: unknown): AgentExecutionOperation | null {
  if (!value || typeof value !== 'object') {
    return null;
  }

  const record = value as Record<string, unknown>;
  const type = String(record.type ?? '').trim();
  const path = String(record.path ?? '').trim();
  const rationale = String(record.rationale ?? '').trim();
  const content = typeof record.content === 'string' ? record.content : undefined;

  if (!path || (type !== 'write_file' && type !== 'delete_path')) {
    return null;
  }

  return {
    type,
    path,
    content,
    rationale: rationale || 'Generated by Gemma.',
  };
}

export async function draftGemmaAgentPlan(request: AgentRequest): Promise<AgentPlan> {
  const apiKey = await getBringYourOwnKey();
  if (!apiKey) {
    throw new Error('Add a Gemma BYOK key before drafting a live plan.');
  }

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMMA_MODEL}:generateContent?key=${encodeURIComponent(apiKey)}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        systemInstruction: {
          parts: [
            {
              text:
                'You are a coding agent planner for a phone-based workspace app. Return only valid JSON with keys summary, filesToCreate, filesToModify, filesToDelete, commands. Use only arrays of strings for file and command lists. Keep commands minimal and avoid destructive steps unless the prompt clearly requires them.',
            },
          ],
        },
        contents: [
          {
            role: 'user',
            parts: [
              {
                text: [
                  `Project name: ${request.projectName}`,
                  `Project path: ${request.projectPath}`,
                  `Granted permissions: ${request.permissions.join(', ') || 'none'}`,
                  'Workspace tree:',
                  request.workspaceTree.join('\n') || '(empty project)',
                  `Task: ${request.prompt}`,
                ].join('\n\n'),
              },
            ],
          },
        ],
        generationConfig: {
          responseMimeType: 'application/json',
          temperature: 0.2,
          thinkingConfig: {
            thinkingLevel: 'high',
          },
        },
      }),
    },
  );

  if (!response.ok) {
    throw new Error(`Gemma request failed with HTTP ${response.status}: ${await response.text()}`);
  }

  const payload = (await response.json()) as {
    candidates?: Array<{
      content?: {
        parts?: Array<{ text?: string }>;
      };
    }>;
  };

  const rawResponse =
    payload.candidates?.flatMap((candidate) => candidate.content?.parts ?? []).map((part) => part.text ?? '').join('\n') ?? '';
  if (!rawResponse.trim()) {
    throw new Error('Gemma returned an empty response.');
  }

  const parsed = JSON.parse(extractJsonBlock(rawResponse)) as Record<string, unknown>;
  return {
    summary: String(parsed.summary ?? 'Gemma returned a plan.'),
    filesToCreate: toStringArray(parsed.filesToCreate),
    filesToModify: toStringArray(parsed.filesToModify),
    filesToDelete: toStringArray(parsed.filesToDelete),
    commands: toStringArray(parsed.commands),
    rawResponse,
  };
}

export async function generateGemmaExecutionPlan(request: AgentExecutionRequest): Promise<AgentExecutionPlan> {
  const apiKey = await getBringYourOwnKey();
  if (!apiKey) {
    throw new Error('Add a Gemma BYOK key before generating real file operations.');
  }

  const response = await fetch(
    `https://generativelanguage.googleapis.com/v1beta/models/${GEMMA_MODEL}:generateContent?key=${encodeURIComponent(apiKey)}`,
    {
      method: 'POST',
      headers: {
        'Content-Type': 'application/json',
      },
      body: JSON.stringify({
        systemInstruction: {
          parts: [
            {
              text:
                'You are a coding agent that must return only valid JSON with keys summary and operations. operations must be an array of objects. Each object must have type, path, rationale, and for write_file also content. Allowed operation types are write_file and delete_path. Only produce operations for approved paths. write_file must contain the full final file content, not a diff. Never emit terminal commands.',
            },
          ],
        },
        contents: [
          {
            role: 'user',
            parts: [
              {
                text: [
                  `Project name: ${request.projectName}`,
                  `Project path: ${request.projectPath}`,
                  `Granted permissions: ${request.permissions.join(', ') || 'none'}`,
                  `Approved create paths: ${request.approvedCreates.join(', ') || 'none'}`,
                  `Approved modify paths: ${request.approvedModifies.join(', ') || 'none'}`,
                  `Approved delete paths: ${request.approvedDeletes.join(', ') || 'none'}`,
                  'Workspace tree:',
                  request.workspaceTree.join('\n') || '(empty project)',
                  'Existing file context:',
                  request.fileContext.length
                    ? request.fileContext
                        .map((file) => [`FILE: ${file.path}`, file.content].join('\n'))
                        .join('\n\n---\n\n')
                    : '(no existing file contents were required)',
                  `Task: ${request.prompt}`,
                ].join('\n\n'),
              },
            ],
          },
        ],
        generationConfig: {
          responseMimeType: 'application/json',
          temperature: 0.1,
        },
      }),
    },
  );

  if (!response.ok) {
    throw new Error(`Gemma execution request failed with HTTP ${response.status}: ${await response.text()}`);
  }

  const payload = (await response.json()) as {
    candidates?: Array<{
      content?: {
        parts?: Array<{ text?: string }>;
      };
    }>;
  };

  const rawResponse =
    payload.candidates?.flatMap((candidate) => candidate.content?.parts ?? []).map((part) => part.text ?? '').join('\n') ?? '';
  if (!rawResponse.trim()) {
    throw new Error('Gemma returned an empty execution response.');
  }

  const parsed = JSON.parse(extractJsonBlock(rawResponse)) as Record<string, unknown>;
  const operations = Array.isArray(parsed.operations)
    ? parsed.operations.map(normalizeOperation).filter((item): item is AgentExecutionOperation => Boolean(item))
    : [];

  return {
    summary: String(parsed.summary ?? 'Gemma returned an execution plan.'),
    operations,
    rawResponse,
  };
}
